@hostUrl = http://localhost:5002

### Health check
GET {{hostUrl}}/health
Accept: application/json

### Open Api Json
GET {{hostUrl}}/openapi/v1.json
Accept: application/json

### Get all bills
GET {{hostUrl}}/bills
Accept: application/json

### Get bill by id
GET {{hostUrl}}/bills/1
Accept: application/json

### Create new bill
POST {{hostUrl}}/bills
Content-Type: application/json

{
  "Name": "New Bill"
}

### Update bill
PUT {{hostUrl}}/bills/1
Content-Type: application/json

{
  "Name": "Updated Bill"
}

### Delete bill
DELETE {{hostUrl}}/bills/1
Accept: application/json
