global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          alias: prometheus

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          alias: grafana

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
        labels:
          alias: tempo

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
        labels:
          alias: loki

  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
        labels:
          alias: otel-collector
