apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
    version: 7
    editable: true

  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id"
          matcherType: label
          name: Trace ID
          url: "$${__value.raw}"
          urlDisplayLabel: Tempo
    version: 5
    editable: true

  - name: tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: "service-name"
            operator: "="
            scope: "resource"
            tag: "service.name"
          - id: "span-name"
            operator: "="
            scope: "span"
            tag: "name"
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: false
        query: "{$${__tags}} | trace_id=`$${__span.traceId}` | span_id=`$${__span.spanId}`"
        spanEndTimeShift: "30m"
        spanStartTimeShift: "-30m"
        tags: []
    version: 17
    editable: true
